implement metatools
CruGlobal/mobile-content-api pull request #967
Opened 2022-05-10 18:56 UTC by andrewroth

2022-05-11 13:02 UTC, knutsenm requested changes

2022-05-11 16:07 UTC, andrewroth commented on spec/acceptance/resources_controller_spec.rb
> +      expect(metatool["relationships"]["variants"]["data"]).to eq([{"id" => "1", "type" => "resource"}, {"id" => "5", "type" => "resource"}])
I didn't specify the order in has_many :variants, so I guess it could return in any order

2022-05-11 17:17 UTC, frett commented on spec/acceptance/resources_controller_spec.rb
> +      expect(metatool["relationships"]["variants"]["data"]).to eq([{"id" => "1", "type" => "resource"}, {"id" => "5", "type" => "resource"}])
from a client perspective the order doesn't matter

2022-05-11 17:48 UTC, knutsenm commented on spec/acceptance/resources_controller_spec.rb
> +      expect(metatool["relationships"]["variants"]["data"]).to eq([{"id" => "1", "type" => "resource"}, {"id" => "5", "type" => "resource"}])
I'm sure it doesn't. I was asking if the test was brittle.

2022-05-18 16:10 UTC, knutsenm commented on db/schema.rb
> +    t.bigint "metatool_id"
Turns out this is normal with modern Rails.

2022-05-30 18:47 UTC, knutsenm approved these changes

2022-05-31 18:27 UTC, frett commented
@andrewroth @knutsenm we should be good to merge this to master whenever you are ready. I'm hoping to push out the admin tool updates to production in the next couple days.

2022-05-31 19:44 UTC, merged